[Party]
; Active party Pals.
; Time in seconds; 0 = instant revive / 60 = 1 minute, 120 = 2 minutes etc. 600 is vanilla (10 minutes)
Enabled = true
ReviveSeconds = 30

[Base]
; Owned Pals outside the party, including base workers and Palbox storage.
; Time in seconds; 0 = instant revive / 60 = 1 minute, 120 = 2 minutes etc. 600 is vanilla (10 minutes)
Enabled = true
ReviveSeconds = 60
