-- Bootstrap catalog for existing settings. Runtime discoveries are maintained in Scripts/Data/catalog-cache.tsv.
return {
    { id = "LuxuryMedicines", name = "High Grade Medical Supplies", category = "Medical" },
    { id = "Herbs", name = "Low Grade Medical Supplies", category = "Medical" },
    { id = "Medicines", name = "Medical Supplies", category = "Medical" },
    { id = "StatusPointResetSan", name = "Memory Wiping Medicine", category = "Medical" },
    { id = "MindControlDrug", name = "Mind Control Meds", category = "Medical" },
    { id = "MushroomJuice", name = "Mysterious Mushroom Juice", category = "Medical" },
    { id = "Supplement", name = "Nutrient Tonic", category = "Medical" },
    { id = "Narcotic", name = "Strange Juice", category = "Medical" },
    { id = "Opium", name = "Suspicious Juice", category = "Medical" },
    { id = "Potion_Extreme", name = "Advanced Recovery Meds", category = "Recovery" },
    { id = "Potion_High", name = "High Quality Recovery Meds", category = "Recovery" },
    { id = "Potion_Low", name = "Low Quality Recovery Meds", category = "Recovery" },
    { id = "PalHealingGrenade", name = "Pal Recovery Grenade", category = "Recovery" },
    { id = "Potion", name = "Recovery Meds", category = "Recovery" },
    { id = "PalRevive", name = "Revival Potion", category = "Recovery" },
    { id = "Elixir_weight_01", name = "Burden Remedy", category = "Remedies" },
    { id = "Elixir_attack_01", name = "Might Remedy", category = "Remedies" },
    { id = "Elixir_workspeed_01", name = "Speed Remedy", category = "Remedies" },
    { id = "Elixir_stamina_01", name = "Stamina Remedy", category = "Remedies" },
    { id = "Elixir_hp_01", name = "Vital Remedy", category = "Remedies" },
    { id = "Elixir_weight_02", name = "Burden Elixir", category = "Elixirs" },
    { id = "Elixir_attack_02", name = "Might Elixir", category = "Elixirs" },
    { id = "Elixir_workspeed_02", name = "Speed Elixir", category = "Elixirs" },
    { id = "Elixir_stamina_02", name = "Stamina Elixir", category = "Elixirs" },
    { id = "Elixir_hp_02", name = "Vital Elixir", category = "Elixirs" },
    { id = "PalAwakening_Dark", name = "Dark Awakening Crystal", category = "PalEnhancements" },
    { id = "PalAwakening_Dragon", name = "Dragon Awakening Crystal", category = "PalEnhancements" },
    { id = "PalAwakening_Electric", name = "Electric Awakening Crystal", category = "PalEnhancements" },
    { id = "PalAwakening_Fire", name = "Fire Awakening Crystal", category = "PalEnhancements" },
    { id = "PalUpgradeStone4", name = "Giant Pal Soul", category = "PalEnhancements" },
    { id = "PalAwakening_Grass", name = "Grass Awakening Crystal", category = "PalEnhancements" },
    { id = "PalAwakening_Ground", name = "Ground Awakening Crystal", category = "PalEnhancements" },
    { id = "PalAwakening_Ice", name = "Ice Awakening Crystal", category = "PalEnhancements" },
    { id = "PalUpgradeStone3", name = "Large Pal Soul", category = "PalEnhancements" },
    { id = "Fruit_hp_01", name = "Life Fruit", category = "PalEnhancements" },
    { id = "PalUpgradeStone2", name = "Medium Pal Soul", category = "PalEnhancements" },
    { id = "PalAwakening_Neutral", name = "Neutral Awakening Crystal", category = "PalEnhancements" },
    { id = "Fruit_attack_01", name = "Power Fruit", category = "PalEnhancements" },
    { id = "PalUpgradeStone", name = "Small Pal Soul", category = "PalEnhancements" },
    { id = "Fruit__defense_01", name = "Stout Fruit", category = "PalEnhancements" },
    { id = "ExpBoost_03", name = "Training Manual (L)", category = "PalEnhancements" },
    { id = "ExpBoost_04", name = "Training Manual (XL)", category = "PalEnhancements" },
    { id = "PalAwakening_Water", name = "Water Awakening Crystal", category = "PalEnhancements" },
    { id = "PalSphere_Ancient_2", name = "Ancient Sphere", category = "Spheres" },
    { id = "PalSphere_Exotic", name = "Exotic Sphere", category = "Spheres" },
    { id = "PalSphere_Giga", name = "Giga Sphere", category = "Spheres" },
    { id = "PalSphere_Tera", name = "Hyper Sphere", category = "Spheres" },
    { id = "PalSphere_Legend", name = "Legendary Sphere", category = "Spheres" },
    { id = "PalSphere_Mega", name = "Mega Sphere", category = "Spheres" },
    { id = "PalSphere", name = "Pal Sphere", category = "Spheres" },
    { id = "PalSphere_Ancient_1", name = "Sol Sphere", category = "Spheres" },
    { id = "PalSphere_Ultimate", name = "Ultimate Sphere", category = "Spheres" },
    { id = "PalSphere_Master", name = "Ultra Sphere", category = "Spheres" },
    { id = "SFArrow", name = "Advanced Arrow", category = "Ammunition" },
    { id = "Arrow", name = "Arrow", category = "Ammunition" },
    { id = "AssaultRifleBullet", name = "Assault Rifle Ammo", category = "Ammunition" },
    { id = "BeamLauncherBullet", name = "Beam Launcher Ammo", category = "Ammunition" },
    { id = "WidePenetrateShotgunBullet", name = "Beam Scatter Ammo", category = "Ammunition" },
    { id = "PalDopingShotBullet", name = "Boost Gun Ammo", category = "Ammunition" },
    { id = "ChargeLaserRifleBullet", name = "Charge Rifle Ammo", category = "Ammunition" },
    { id = "RoughBullet", name = "Coarse Ammo", category = "Ammunition" },
    { id = "SkySubmachineGunBullet", name = "Combat SMG Ammo", category = "Ammunition" },
    { id = "InkBullet", name = "Decal Ink", category = "Ammunition" },
    { id = "LaserBullet", name = "Energy Cartridge", category = "Ammunition" },
    { id = "EnergyShotgunBullet", name = "Energy Shotgun Ammo", category = "Ammunition" },
    { id = "Arrow_Fire", name = "Fire Arrow", category = "Ammunition" },
    { id = "FlamethrowerBullet", name = "Flamethrower Fuel", category = "Ammunition" },
    { id = "GatlingBullet", name = "Gatling Gun Ammo", category = "Ammunition" },
    { id = "GrenadeBullet", name = "Grenade Ammo", category = "Ammunition" },
    { id = "HandgunBullet", name = "Handgun Ammo", category = "Ammunition" },
    { id = "SkyAssaultRifleBullet", name = "Heavy Assault Rifle Ammo", category = "Ammunition" },
    { id = "LaserGatlingBullet", name = "Laser Gatling Cartridge", category = "Ammunition" },
    { id = "SkyBowArrow", name = "Mechanical Bow Ammo", category = "Ammunition" },
    { id = "MeteorBullet", name = "Meteorite Ammo", category = "Ammunition" },
    { id = "MissileBullet", name = "Missile Ammo", category = "Ammunition" },
    { id = "OverheatRifleBullet", name = "Overheat Rifle Ammo", category = "Ammunition" },
    { id = "EnergyLauncherBullet", name = "Plasma Cartridge", category = "Ammunition" },
    { id = "ElectricArcAssaultRifleBullet", name = "Plasma Rifle Ammo", category = "Ammunition" },
    { id = "Arrow_Poison", name = "Poison Arrow", category = "Ammunition" },
    { id = "SkyShotgunBullet", name = "Prototype Shotgun Ammo", category = "Ammunition" },
    { id = "ReinforcedArrow", name = "Reinforced Arrow", category = "Ammunition" },
    { id = "RifleBullet", name = "Rifle Ammo", category = "Ammunition" },
    { id = "ExplosiveBullet", name = "Rocket Ammo", category = "Ammunition" },
    { id = "ShotgunBullet", name = "Shotgun Shell", category = "Ammunition" },
    { id = "SkyLightBullet", name = "Sunreach Rapid-Fire Ammo", category = "Ammunition" },
    { id = "SkyHeavyBullet", name = "Sunreach Single-Shot Ammo", category = "Ammunition" },
    { id = "SkyGrenadeLauncherBullet", name = "Tactical Grenade Launcher Ammo", category = "Ammunition" },
    { id = "FragGrenade_Dark", name = "Dark Grenade", category = "Grenades" },
    { id = "FragGrenade_Dragon", name = "Dragon Grenade", category = "Grenades" },
    { id = "FragGrenade", name = "Frag Grenade", category = "Grenades" },
    { id = "FragGrenade_Super", name = "Frag Grenade Mk2", category = "Grenades" },
    { id = "FragGrenade_Leaf", name = "Grass Grenade", category = "Grenades" },
    { id = "FragGrenade_Ground", name = "Ground Grenade", category = "Grenades" },
    { id = "FragGrenade_Ice", name = "Ice Grenade", category = "Grenades" },
    { id = "FragGrenade_Fire", name = "Incendiary Grenade", category = "Grenades" },
    { id = "FragGrenade_Elec", name = "Shock Grenade", category = "Grenades" },
    { id = "FragGrenade_Water", name = "Water Grenade", category = "Grenades" },
    { id = "AIcore", name = "AI Core", category = "Materials" },
    { id = "Bio_Battery", name = "Bio Battery", category = "Materials" },
    { id = "CarbonFiber", name = "Carbon Fiber", category = "Materials" },
    { id = "Cement", name = "Cement", category = "Materials" },
    { id = "MachineParts2", name = "Circuit Board", category = "Materials" },
    { id = "Cloth", name = "Cloth", category = "Materials" },
    { id = "Computer", name = "Computer", category = "Materials" },
    { id = "Corrosive_Solvent", name = "Corrosive Solvent", category = "Materials" },
    { id = "Bio_Coolant", name = "Cryogenic Coolant", category = "Materials" },
    { id = "Fiber", name = "Fiber", category = "Materials" },
    { id = "Gunpowder2", name = "Gunpowder", category = "Materials" },
    { id = "Cloth2", name = "High Quality Cloth", category = "Materials" },
    { id = "HighGrade_Processed_Wood", name = "High Quality Wooden Board", category = "Materials" },
    { id = "Premium_Processed_Wood", name = "Mythical Wooden Board", category = "Materials" },
    { id = "MachineParts", name = "Nail", category = "Materials" },
    { id = "Pal_crystal_S", name = "Paldium Fragment", category = "Materials" },
    { id = "Polymer", name = "Polymer", category = "Materials" },
    { id = "Thermal_Core", name = "Thermal Core", category = "Materials" },
    { id = "Processed_Wood", name = "Wooden Board", category = "Materials" },
    { id = "Charcoal", name = "Charcoal", category = "Ingots" },
    { id = "ManganeseIngot", name = "Coralum Ingot", category = "Ingots" },
    { id = "StainlessSteel", name = "Hexolite", category = "Ingots" },
    { id = "CopperIngot", name = "Ingot", category = "Ingots" },
    { id = "StealIngot", name = "Pal Metal Ingot", category = "Ingots" },
    { id = "WorldTreeIngot", name = "Paloxite Ingot", category = "Ingots" },
    { id = "Plastic", name = "Plasteel", category = "Ingots" },
    { id = "IronIngot", name = "Refined Ingot", category = "Ingots" },
    { id = "SkyislandIngot", name = "Soralite Ingot", category = "Ingots" },
    { id = "FishingBait_3_A", name = "Alluring Bait", category = "FishingBait" },
    { id = "FishingBait_1_A", name = "Beginner Bait", category = "FishingBait" },
    { id = "FishingBait_3", name = "Deluxe Bait", category = "FishingBait" },
    { id = "FishingBait_2", name = "High Quality Bait", category = "FishingBait" },
    { id = "FishingBait_2_A", name = "Lucky Bait", category = "FishingBait" },
    { id = "FishingBait_2_B", name = "Quick Bait", category = "FishingBait" },
    { id = "FishingBait_3_B", name = "Risky Bait", category = "FishingBait" },
    { id = "FishingBait_1", name = "Simple Bait", category = "FishingBait" },
    { id = "FishingBait_1_B", name = "Sweet Bait", category = "FishingBait" },
    { id = "Baked_Berries", name = "Baked Berries", category = "Food" },
    { id = "BakedMushroom", name = "Baked Mushroom", category = "Food" },
    { id = "Pan", name = "Bread", category = "Food" },
    { id = "BakedMeat_LazyCatfish", name = "Broiled Dumud", category = "Food" },
    { id = "Yakisoba", name = "Broncherry Fried Noodles", category = "Food" },
    { id = "BakedMeat_SakuraSaurus", name = "Broncherry Rib Roast", category = "Food" },
    { id = "Cake", name = "Cake", category = "Food" },
    { id = "Carbonara", name = "Carbonara", category = "Food" },
    { id = "ChickenSaute", name = "Chikipi Sauté", category = "Food" },
    { id = "Chowder", name = "Dumud Chowder", category = "Food" },
    { id = "DeerLocoMoco", name = "Eikthyrdeer Loco Moco", category = "Food" },
    { id = "DeerStew", name = "Eikthyrdeer Stew", category = "Food" },
    { id = "Cake04", name = "Extravagant Vegetable Cake", category = "Food" },
    { id = "Flour", name = "Flour", category = "Food" },
    { id = "PotatoChips", name = "French Fries", category = "Food" },
    { id = "FriedChicken", name = "Fried Chikipi", category = "Food" },
    { id = "FriedEggs", name = "Fried Egg", category = "Food" },
    { id = "OctopusGirl_Takoyaki", name = "Fried Gloopie Balls", category = "Food" },
    { id = "FriedKelpie", name = "Fried Kelpsea", category = "Food" },
    { id = "MeatAndPotatoes", name = "Galeclaw Nikujaga", category = "Food" },
    { id = "Gratin", name = "Gratin", category = "Food" },
    { id = "BakedMeat_ChickenPal", name = "Grilled Chikipi", category = "Food" },
    { id = "BakedMeat_Eagle", name = "Grilled Galeclaw", category = "Food" },
    { id = "BakedMeat_Kelpie", name = "Grilled Kelpsea", category = "Food" },
    { id = "GenghisKhan", name = "Grilled Lamball", category = "Food" },
    { id = "BakedMeat_BerryGoat", name = "Herb Roasted Caprity", category = "Food" },
    { id = "GrilledSheepHerbs", name = "Herb Roasted Lamball", category = "Food" },
    { id = "Hotmilk", name = "Hotmilk", category = "Food" },
    { id = "JamBun", name = "Jam-Filled Bun", category = "Food" },
    { id = "JellyfishFairy_jelly", name = "Jelliette's Jiggly Jelly", category = "Food" },
    { id = "JellyfishGhost_jelly", name = "Jellroy's Jolly Jelly", category = "Food" },
    { id = "BakedMeat_SheepBall", name = "Lamball Kebab", category = "Food" },
    { id = "Curry", name = "Mammorest Curry", category = "Food" },
    { id = "BakedMeat_GrassMammoth", name = "Mammorest Steak", category = "Food" },
    { id = "MarinatedMushrooms", name = "Marinated Mushrooms", category = "Food" },
    { id = "Minestrone", name = "Minestrone", category = "Food" },
    { id = "Cheeseburger_2", name = "Mozzarina Cheeseburger", category = "Food" },
    { id = "Hamburger_2", name = "Mozzarina Hamburger", category = "Food" },
    { id = "BakedMeat_CowPal", name = "Mozzarina Steak", category = "Food" },
    { id = "BakedMeat_IceCrocodile", name = "Munchill Steak", category = "Food" },
    { id = "Cake02", name = "Mushroom Cake", category = "Food" },
    { id = "Quiche", name = "Mushroom Quiche", category = "Food" },
    { id = "MushroomSoup", name = "Mushroom Soup", category = "Food" },
    { id = "Omelet", name = "Omelet", category = "Food" },
    { id = "Pancake", name = "Pancake", category = "Food" },
    { id = "Pizza", name = "Pizza", category = "Food" },
    { id = "StewedIceDeer", name = "Reindrix Stew", category = "Food" },
    { id = "BakedMeat_Deer", name = "Roast Eikthyrdeer", category = "Food" },
    { id = "BakedMeat_IceDeer", name = "Roast Reindrix", category = "Food" },
    { id = "BakedMeat_Boar", name = "Roast Rushoar", category = "Food" },
    { id = "BaconEggs", name = "Rushoar Bacon 'n' Eggs", category = "Food" },
    { id = "Gyoza", name = "Rushoar Gyoza", category = "Food" },
    { id = "HotDog_2", name = "Rushoar Hot Dog", category = "Food" },
    { id = "Salad", name = "Salad", category = "Food" },
    { id = "GrilledSwordCutlassFish", name = "Salt-Grilled Skutlass", category = "Food" },
    { id = "OctopusGirl_Takoyaki2", name = "Seafood Pasta", category = "Food" },
    { id = "Seafood_Salada", name = "Seafood Salad", category = "Food" },
    { id = "Cake05", name = "Special Cake", category = "Food" },
    { id = "SpringRolls", name = "Spring Rolls", category = "Food" },
    { id = "Eaglestew", name = "Stewed Galeclaw", category = "Food" },
    { id = "StirFriedVegetables", name = "Stir-Fried Vegetables", category = "Food" },
    { id = "Cake03", name = "Vegetable Cake", category = "Food" },
    { id = "PalSummon_NightLady_Dark_2", name = "Bellanoir Libero (Ultra) Slab", category = "Summoning" },
    { id = "PalSummon_NightLady_Dark", name = "Bellanoir Libero's Slab", category = "Summoning" },
    { id = "PalSummon_NightLady", name = "Bellanoir's Slab", category = "Summoning" },
    { id = "PalSummon_KingBahamut_Dragon_2", name = "Blazamut Ryu (Ultra) Slab", category = "Summoning" },
    { id = "PalSummon_KingBahamut_Dragon", name = "Blazamut Ryu Slab", category = "Summoning" },
    { id = "PalSummon_YakushimaBoss002", name = "Celestial Sigil", category = "Summoning" },
    { id = "PalSummon_LegendDeer_2", name = "Hartalis (Ultra) Slab", category = "Summoning" },
    { id = "PalSummon_LegendDeer", name = "Hartalis Slab", category = "Summoning" },
    { id = "PalSummon_DarkMechaDragon_2", name = "Xenolord (Ultra) Slab", category = "Summoning" },
    { id = "PalSummon_DarkMechaDragon", name = "Xenolord Slab", category = "Summoning" },
    { id = "Salvage_TreasureBoxKey01", name = "Fishing Magnet", category = "Utilities" },
    { id = "Homeward", name = "Homeward Thundercloud", category = "Utilities" },
    { id = "Salvage_TreasureBoxKey02", name = "Powerful Fishing Magnet", category = "Utilities" },
    { id = "WingGlider_Fuel", name = "Wing Cell", category = "Utilities" },
    { id = "Money", name = "Gold Coin", category = "Currency" },
}
